services:
  catalog-api:
    image: ${DOCKER_REGISTRY-}catalog-api
    build:
      context: .
      dockerfile: ./src/Services/Catalog/Catalog.API/Dockerfile
  catalog_db:
        container_name: catalog-db-dev
        image: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=12345678
            - POSTGRES_DB=catalog-db
        restart: always
        ports:
            - "7101:5432"
        volumes:
            - postgres_catalog:/var/lib/postgresql/data/
volumes:
    postgres_catalog:    
    